### PR TITLE
fix bad prism-element path

### PR DESCRIPTION
**Pull request by FredKSchott**
This was messing up some hydrolysis analysis in tedium

### CODE REVIEW

**Comment by notwaldorf** [comment]
LGTM!

**Comment by FredKSchott** [comment]
*goes through his old PRs*

@notwaldorf can you merge? I have no write access

**Comment by notwaldorf** [comment]
@FredKSchott Done done done! Does it need a release?

**Comment by FredKSchott** [comment]
Nope! Thanks @notwaldorf

**Pull request merged**
